CREATE DATABASE Dati;

USE Dati;

CREATE TABLE User(
	cod INT(10) NOT NULL PRIMARY KEY,
	FirstName VARCHAR(15) DEFAULT NULL,
	LastName VARCHAR(20) DEFAULT NULL,
	age INT(2) DEFAULT NULL,
	FOREIGN KEY(cod) REFERENCES Login(id)
	);
CREATE TABLE Login(
	id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT
	email VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(10) NOT NULL

CREATE TABLE Post(
	id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	author INT(10) NOT NULL PRIMARY KEY,	
	date DATE NOT NULL,
	city VARCHAR(20) NOT NULL,
	img_path VARCHAR(50) NOT NULL,
	FOREIGN KEY(author) REFERENCES User(id)
);

CREATE TABLE Rating(
	codPost INT(10) NOT NULL PRIMARY KEY ,
	codUser INT(10) NOT NULL PRIMARY KEY,
	rat INT(5) NOT NULL,
	FOREIGN KEY(codUser) REFERENCES User(id),
	FOREIGN KEY(codPost) REFERENCES Post(id),
);

